### PR TITLE
Update StringProcessor.java

### PR DESCRIPTION
**Pull request by Toffu-BlankieChoccy**
Need comment

### CODE REVIEW

**Comment by Toffu-BlankieChoccy** [comment]
Yolohellohilo

**Comment by Skrawrz** [comment]
alo alo alo alo

**Comment by Toffu-BlankieChoccy** [comment]
> alo alo alo alo

câm

**Comment by Araxys123** [comment]
:)))

**Comment by huyhakwalker** [comment]
that's the good thing  i've ever seen

**Comment by Toffu-BlankieChoccy** [comment]
> that's the good thing i've ever seen

That's the best thing I've ever seen. M có chắc là định đi thi TOIEC ko

**Comment by huyhakwalker** [comment]
sao lại best

**Comment by Toffu-BlankieChoccy** [comment]
> sao lại best

khi m bảo I have ever seen nghĩa là những gì m đã seen nó không bằng cái thing m đang mô tả. M đang so sánh đó.
Ở đây best mới đúng

**Comment by huyhakwalker** [comment]
oh, thanks

**Comment by Araxys123** [comment]
Good code overall, but I have some suggestions for you:
1. Change the `characterFrequency` method to return a `Map<Character, Integer>` instead of printing the results directly to the console. (Line 50)

2. Prevent `NullPointerException` by adding null checks in the constructor and methods. (Line 1)

Good luck.

**Pull request merged**
